name: overhead-norm-strategies
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - pip
  - python==3.7.6
  - cudnn=7.6.5=cuda10.0_0
  - tensorflow-gpu==1.15.0
  - keras==2.2.4
  - h5py==2.10
  - pip:
    - scikit-image==0.16.2
    - scikit-learn==0.22.2.post1
    - rasterio==1.2.3
    - opencv-python
